---
title: "Assignment 3"
author: "Tirza IJpma, Mick IJzer and Maud van den Berg"
date: "3/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
3. africa

```{r}
africa = read.table("africa.txt", header = T)
#acquiring data
attach(africa)
N = length(miltcoup)
hist(miltcoup)
meanMilt = mean(miltcoup)
varMilt = var(miltcoup) #overdispersion
mod = glm(miltcoup~oligarchy+pollib+parties+pctvote+popn+size+numelec+numregim, family=poisson, data = africa)
summary(mod)
#sigma = 28.668/27 #greater then 1--> overdispersion
#to fix std. error
#mod2 = glm(miltcoup~oligarchy+pollib+parties+pctvote+popn+size+numelec+numregim, family=quasipoisson, data = africa)
#summary(mod2)
conf = confint(mod)
co1 = coef(mod)
plot(fitted(mod),residuals(mod))
plot(log(fitted(mod),residuals(mod))) #--> raar??
```

b)
```{r}
attach(africa)
#step-down method
summary(glm(miltcoup~oligarchy+pollib+parties+pctvote+popn+size+numelec+numregim, family=poisson, data = africa))
#numelec is most insiginificant, so take out 
summary(glm(miltcoup~oligarchy+pollib+parties+pctvote+popn+size+numregim, family=poisson, data = africa))
#numregim out 
summary(glm(miltcoup~oligarchy+pollib+parties+pctvote+popn+size, family=poisson, data = africa))
#size out
summary(glm(miltcoup~oligarchy+pollib+parties+pctvote+popn, family=poisson, data = africa))
#popn out
summary(glm(miltcoup~oligarchy+pollib+parties+pctvote, family=poisson, data = africa))
#pctvote out
summary(glm(miltcoup~oligarchy+pollib+parties, family=poisson, data = africa))
#all significant except intercept


```

